// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA22BHCwIYc_6-ND0_pemIjm0mZtp_htHY',
    appId: '1:65823745012:web:b1e3e15e4a526e901acfa1',
    messagingSenderId: '65823745012',
    projectId: 'whachadoin-tracker-798',
    authDomain: 'whachadoin-tracker-798.firebaseapp.com',
    storageBucket: 'whachadoin-tracker-798.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDMIqw3EKlfh42vn-qoa-dTbSVlhvwAo',
    appId: '1:65823745012:android:2126cc19d753315b1acfa1',
    messagingSenderId: '65823745012',
    projectId: 'whachadoin-tracker-798',
    storageBucket: 'whachadoin-tracker-798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnuO-uiMlwOwvNZhihf2PGVFblHzm3ZoA',
    appId: '1:65823745012:ios:0d6db63ca0a57ae31acfa1',
    messagingSenderId: '65823745012',
    projectId: 'whachadoin-tracker-798',
    storageBucket: 'whachadoin-tracker-798.firebasestorage.app',
    iosClientId: '65823745012-jh50sal6fev2f7gapqi8r6oloa0vred8.apps.googleusercontent.com',
    iosBundleId: 'com.casey.whacha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnuO-uiMlwOwvNZhihf2PGVFblHzm3ZoA',
    appId: '1:65823745012:ios:0d6db63ca0a57ae31acfa1',
    messagingSenderId: '65823745012',
    projectId: 'whachadoin-tracker-798',
    storageBucket: 'whachadoin-tracker-798.firebasestorage.app',
    iosClientId: '65823745012-jh50sal6fev2f7gapqi8r6oloa0vred8.apps.googleusercontent.com',
    iosBundleId: 'com.casey.whacha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA22BHCwIYc_6-ND0_pemIjm0mZtp_htHY',
    appId: '1:65823745012:web:5efea5442d7ce1f41acfa1',
    messagingSenderId: '65823745012',
    projectId: 'whachadoin-tracker-798',
    authDomain: 'whachadoin-tracker-798.firebaseapp.com',
    storageBucket: 'whachadoin-tracker-798.firebasestorage.app',
  );
}
